# Generated by Django 4.2.3 on 2023-08-11 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_agreement_accepted_customuser_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETMInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etm_username', models.CharField(max_length=100)),
                ('etm_password', models.CharField(max_length=100)),
                ('agreement_checked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
