# Generated by Django 4.2.3 on 2023-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_etminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacation_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reg_hours_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missed_hours_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missed_dates', models.TextField()),
            ],
        ),
    ]
