# Generated by Django 4.2.3 on 2023-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_employeerecord_user_name_employeerecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerecord',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
    ]
