# Generated by Django 4.2.3 on 2023-08-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
    ]
