# Generated by Django 4.2.3 on 2023-08-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
